---

- hosts: all
  become: true
  tasks:

  - name: update repository index 
    apt:
      update_cache: yes #sunucuları günceller

  - name: install apache2 package #ne yaptığına dair isim
    apt:
      name: apache2 #apache kurar
      state: absent #durum yok anlamına gelir. paketi kaldırır

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent