---

- hosts: all
  become: true
  tasks:

  - name: update repository index 
    apt:
      update_cache: yes #sunucuları günceller
    when: ansible_distribution in ["Ubuntu", "Debian"] #iki farklı dağıtıma sahipsek bunları her iki dağıtım içinde çalıştıracaktır.

  - name: install apache2 package #ne yaptığına dair isim
    apt:
      name: apache2 #apache kurar
      state: latest #paketlerin en son sürümü olduğuna emin ol
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distrubition in ["Ubuntu", "Debian"]